/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ServicesWellnessRouteImport } from './routes/services.wellness'
import { Route as ServicesSurgeryRouteImport } from './routes/services.surgery'
import { Route as ServicesSkinRouteImport } from './routes/services.skin'
import { Route as ServicesLiftingRouteImport } from './routes/services.lifting'
import { Route as ServicesLaserRouteImport } from './routes/services.laser'
import { Route as ServicesInjectablesRouteImport } from './routes/services.injectables'
import { Route as ServicesAestheticRouteImport } from './routes/services.aesthetic'
import { Route as AdminSeoRouteImport } from './routes/admin.seo'
import { Route as ServicesLaserHairRemovalRouteImport } from './routes/services.laser.hair-removal'
import { Route as ServicesDentalClinicalDentistryRouteImport } from './routes/services.dental.clinical-dentistry'
import { Route as ServicesDentalAestheticDentistryRouteImport } from './routes/services.dental.aesthetic-dentistry'

const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesWellnessRoute = ServicesWellnessRouteImport.update({
  id: '/wellness',
  path: '/wellness',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesSurgeryRoute = ServicesSurgeryRouteImport.update({
  id: '/surgery',
  path: '/surgery',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesSkinRoute = ServicesSkinRouteImport.update({
  id: '/skin',
  path: '/skin',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesLiftingRoute = ServicesLiftingRouteImport.update({
  id: '/lifting',
  path: '/lifting',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesLaserRoute = ServicesLaserRouteImport.update({
  id: '/laser',
  path: '/laser',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesInjectablesRoute = ServicesInjectablesRouteImport.update({
  id: '/injectables',
  path: '/injectables',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesAestheticRoute = ServicesAestheticRouteImport.update({
  id: '/aesthetic',
  path: '/aesthetic',
  getParentRoute: () => ServicesRoute,
} as any)
const AdminSeoRoute = AdminSeoRouteImport.update({
  id: '/admin/seo',
  path: '/admin/seo',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesLaserHairRemovalRoute =
  ServicesLaserHairRemovalRouteImport.update({
    id: '/hair-removal',
    path: '/hair-removal',
    getParentRoute: () => ServicesLaserRoute,
  } as any)
const ServicesDentalClinicalDentistryRoute =
  ServicesDentalClinicalDentistryRouteImport.update({
    id: '/dental/clinical-dentistry',
    path: '/dental/clinical-dentistry',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesDentalAestheticDentistryRoute =
  ServicesDentalAestheticDentistryRouteImport.update({
    id: '/dental/aesthetic-dentistry',
    path: '/dental/aesthetic-dentistry',
    getParentRoute: () => ServicesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/services': typeof ServicesRouteWithChildren
  '/admin/seo': typeof AdminSeoRoute
  '/services/aesthetic': typeof ServicesAestheticRoute
  '/services/injectables': typeof ServicesInjectablesRoute
  '/services/laser': typeof ServicesLaserRouteWithChildren
  '/services/lifting': typeof ServicesLiftingRoute
  '/services/skin': typeof ServicesSkinRoute
  '/services/surgery': typeof ServicesSurgeryRoute
  '/services/wellness': typeof ServicesWellnessRoute
  '/services/': typeof ServicesIndexRoute
  '/services/dental/aesthetic-dentistry': typeof ServicesDentalAestheticDentistryRoute
  '/services/dental/clinical-dentistry': typeof ServicesDentalClinicalDentistryRoute
  '/services/laser/hair-removal': typeof ServicesLaserHairRemovalRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/admin/seo': typeof AdminSeoRoute
  '/services/aesthetic': typeof ServicesAestheticRoute
  '/services/injectables': typeof ServicesInjectablesRoute
  '/services/laser': typeof ServicesLaserRouteWithChildren
  '/services/lifting': typeof ServicesLiftingRoute
  '/services/skin': typeof ServicesSkinRoute
  '/services/surgery': typeof ServicesSurgeryRoute
  '/services/wellness': typeof ServicesWellnessRoute
  '/services': typeof ServicesIndexRoute
  '/services/dental/aesthetic-dentistry': typeof ServicesDentalAestheticDentistryRoute
  '/services/dental/clinical-dentistry': typeof ServicesDentalClinicalDentistryRoute
  '/services/laser/hair-removal': typeof ServicesLaserHairRemovalRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/services': typeof ServicesRouteWithChildren
  '/admin/seo': typeof AdminSeoRoute
  '/services/aesthetic': typeof ServicesAestheticRoute
  '/services/injectables': typeof ServicesInjectablesRoute
  '/services/laser': typeof ServicesLaserRouteWithChildren
  '/services/lifting': typeof ServicesLiftingRoute
  '/services/skin': typeof ServicesSkinRoute
  '/services/surgery': typeof ServicesSurgeryRoute
  '/services/wellness': typeof ServicesWellnessRoute
  '/services/': typeof ServicesIndexRoute
  '/services/dental/aesthetic-dentistry': typeof ServicesDentalAestheticDentistryRoute
  '/services/dental/clinical-dentistry': typeof ServicesDentalClinicalDentistryRoute
  '/services/laser/hair-removal': typeof ServicesLaserHairRemovalRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/services'
    | '/admin/seo'
    | '/services/aesthetic'
    | '/services/injectables'
    | '/services/laser'
    | '/services/lifting'
    | '/services/skin'
    | '/services/surgery'
    | '/services/wellness'
    | '/services/'
    | '/services/dental/aesthetic-dentistry'
    | '/services/dental/clinical-dentistry'
    | '/services/laser/hair-removal'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/admin/seo'
    | '/services/aesthetic'
    | '/services/injectables'
    | '/services/laser'
    | '/services/lifting'
    | '/services/skin'
    | '/services/surgery'
    | '/services/wellness'
    | '/services'
    | '/services/dental/aesthetic-dentistry'
    | '/services/dental/clinical-dentistry'
    | '/services/laser/hair-removal'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/services'
    | '/admin/seo'
    | '/services/aesthetic'
    | '/services/injectables'
    | '/services/laser'
    | '/services/lifting'
    | '/services/skin'
    | '/services/surgery'
    | '/services/wellness'
    | '/services/'
    | '/services/dental/aesthetic-dentistry'
    | '/services/dental/clinical-dentistry'
    | '/services/laser/hair-removal'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  ServicesRoute: typeof ServicesRouteWithChildren
  AdminSeoRoute: typeof AdminSeoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/wellness': {
      id: '/services/wellness'
      path: '/wellness'
      fullPath: '/services/wellness'
      preLoaderRoute: typeof ServicesWellnessRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/surgery': {
      id: '/services/surgery'
      path: '/surgery'
      fullPath: '/services/surgery'
      preLoaderRoute: typeof ServicesSurgeryRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/skin': {
      id: '/services/skin'
      path: '/skin'
      fullPath: '/services/skin'
      preLoaderRoute: typeof ServicesSkinRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/lifting': {
      id: '/services/lifting'
      path: '/lifting'
      fullPath: '/services/lifting'
      preLoaderRoute: typeof ServicesLiftingRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/laser': {
      id: '/services/laser'
      path: '/laser'
      fullPath: '/services/laser'
      preLoaderRoute: typeof ServicesLaserRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/injectables': {
      id: '/services/injectables'
      path: '/injectables'
      fullPath: '/services/injectables'
      preLoaderRoute: typeof ServicesInjectablesRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/aesthetic': {
      id: '/services/aesthetic'
      path: '/aesthetic'
      fullPath: '/services/aesthetic'
      preLoaderRoute: typeof ServicesAestheticRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/admin/seo': {
      id: '/admin/seo'
      path: '/admin/seo'
      fullPath: '/admin/seo'
      preLoaderRoute: typeof AdminSeoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/laser/hair-removal': {
      id: '/services/laser/hair-removal'
      path: '/hair-removal'
      fullPath: '/services/laser/hair-removal'
      preLoaderRoute: typeof ServicesLaserHairRemovalRouteImport
      parentRoute: typeof ServicesLaserRoute
    }
    '/services/dental/clinical-dentistry': {
      id: '/services/dental/clinical-dentistry'
      path: '/dental/clinical-dentistry'
      fullPath: '/services/dental/clinical-dentistry'
      preLoaderRoute: typeof ServicesDentalClinicalDentistryRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/dental/aesthetic-dentistry': {
      id: '/services/dental/aesthetic-dentistry'
      path: '/dental/aesthetic-dentistry'
      fullPath: '/services/dental/aesthetic-dentistry'
      preLoaderRoute: typeof ServicesDentalAestheticDentistryRouteImport
      parentRoute: typeof ServicesRoute
    }
  }
}

interface ServicesLaserRouteChildren {
  ServicesLaserHairRemovalRoute: typeof ServicesLaserHairRemovalRoute
}

const ServicesLaserRouteChildren: ServicesLaserRouteChildren = {
  ServicesLaserHairRemovalRoute: ServicesLaserHairRemovalRoute,
}

const ServicesLaserRouteWithChildren = ServicesLaserRoute._addFileChildren(
  ServicesLaserRouteChildren,
)

interface ServicesRouteChildren {
  ServicesAestheticRoute: typeof ServicesAestheticRoute
  ServicesInjectablesRoute: typeof ServicesInjectablesRoute
  ServicesLaserRoute: typeof ServicesLaserRouteWithChildren
  ServicesLiftingRoute: typeof ServicesLiftingRoute
  ServicesSkinRoute: typeof ServicesSkinRoute
  ServicesSurgeryRoute: typeof ServicesSurgeryRoute
  ServicesWellnessRoute: typeof ServicesWellnessRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
  ServicesDentalAestheticDentistryRoute: typeof ServicesDentalAestheticDentistryRoute
  ServicesDentalClinicalDentistryRoute: typeof ServicesDentalClinicalDentistryRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesAestheticRoute: ServicesAestheticRoute,
  ServicesInjectablesRoute: ServicesInjectablesRoute,
  ServicesLaserRoute: ServicesLaserRouteWithChildren,
  ServicesLiftingRoute: ServicesLiftingRoute,
  ServicesSkinRoute: ServicesSkinRoute,
  ServicesSurgeryRoute: ServicesSurgeryRoute,
  ServicesWellnessRoute: ServicesWellnessRoute,
  ServicesIndexRoute: ServicesIndexRoute,
  ServicesDentalAestheticDentistryRoute: ServicesDentalAestheticDentistryRoute,
  ServicesDentalClinicalDentistryRoute: ServicesDentalClinicalDentistryRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  ServicesRoute: ServicesRouteWithChildren,
  AdminSeoRoute: AdminSeoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
