/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ServicesWellnessRouteImport } from './routes/services.wellness'
import { Route as ServicesSurgeryRouteImport } from './routes/services.surgery'
import { Route as ServicesSkinRouteImport } from './routes/services.skin'
import { Route as ServicesLiftingRouteImport } from './routes/services.lifting'
import { Route as ServicesLaserRouteImport } from './routes/services.laser'
import { Route as ServicesInjectablesRouteImport } from './routes/services.injectables'
import { Route as ServicesAestheticRouteImport } from './routes/services.aesthetic'
import { Route as ServicesDentalWhiteningRouteImport } from './routes/services.dental.whitening'
import { Route as ServicesDentalOrthodonticsRouteImport } from './routes/services.dental.orthodontics'
import { Route as ServicesDentalImplantsRouteImport } from './routes/services.dental.implants'
import { Route as ServicesDentalGeneralRouteImport } from './routes/services.dental.general'
import { Route as ServicesDentalCosmeticDentistryRouteImport } from './routes/services.dental.cosmetic-dentistry'

const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesWellnessRoute = ServicesWellnessRouteImport.update({
  id: '/wellness',
  path: '/wellness',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesSurgeryRoute = ServicesSurgeryRouteImport.update({
  id: '/surgery',
  path: '/surgery',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesSkinRoute = ServicesSkinRouteImport.update({
  id: '/skin',
  path: '/skin',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesLiftingRoute = ServicesLiftingRouteImport.update({
  id: '/lifting',
  path: '/lifting',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesLaserRoute = ServicesLaserRouteImport.update({
  id: '/laser',
  path: '/laser',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesInjectablesRoute = ServicesInjectablesRouteImport.update({
  id: '/injectables',
  path: '/injectables',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesAestheticRoute = ServicesAestheticRouteImport.update({
  id: '/aesthetic',
  path: '/aesthetic',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesDentalWhiteningRoute = ServicesDentalWhiteningRouteImport.update({
  id: '/dental/whitening',
  path: '/dental/whitening',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesDentalOrthodonticsRoute =
  ServicesDentalOrthodonticsRouteImport.update({
    id: '/dental/orthodontics',
    path: '/dental/orthodontics',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesDentalImplantsRoute = ServicesDentalImplantsRouteImport.update({
  id: '/dental/implants',
  path: '/dental/implants',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesDentalGeneralRoute = ServicesDentalGeneralRouteImport.update({
  id: '/dental/general',
  path: '/dental/general',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesDentalCosmeticDentistryRoute =
  ServicesDentalCosmeticDentistryRouteImport.update({
    id: '/dental/cosmetic-dentistry',
    path: '/dental/cosmetic-dentistry',
    getParentRoute: () => ServicesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/services': typeof ServicesRouteWithChildren
  '/services/aesthetic': typeof ServicesAestheticRoute
  '/services/injectables': typeof ServicesInjectablesRoute
  '/services/laser': typeof ServicesLaserRoute
  '/services/lifting': typeof ServicesLiftingRoute
  '/services/skin': typeof ServicesSkinRoute
  '/services/surgery': typeof ServicesSurgeryRoute
  '/services/wellness': typeof ServicesWellnessRoute
  '/services/': typeof ServicesIndexRoute
  '/services/dental/cosmetic-dentistry': typeof ServicesDentalCosmeticDentistryRoute
  '/services/dental/general': typeof ServicesDentalGeneralRoute
  '/services/dental/implants': typeof ServicesDentalImplantsRoute
  '/services/dental/orthodontics': typeof ServicesDentalOrthodonticsRoute
  '/services/dental/whitening': typeof ServicesDentalWhiteningRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/services/aesthetic': typeof ServicesAestheticRoute
  '/services/injectables': typeof ServicesInjectablesRoute
  '/services/laser': typeof ServicesLaserRoute
  '/services/lifting': typeof ServicesLiftingRoute
  '/services/skin': typeof ServicesSkinRoute
  '/services/surgery': typeof ServicesSurgeryRoute
  '/services/wellness': typeof ServicesWellnessRoute
  '/services': typeof ServicesIndexRoute
  '/services/dental/cosmetic-dentistry': typeof ServicesDentalCosmeticDentistryRoute
  '/services/dental/general': typeof ServicesDentalGeneralRoute
  '/services/dental/implants': typeof ServicesDentalImplantsRoute
  '/services/dental/orthodontics': typeof ServicesDentalOrthodonticsRoute
  '/services/dental/whitening': typeof ServicesDentalWhiteningRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/services': typeof ServicesRouteWithChildren
  '/services/aesthetic': typeof ServicesAestheticRoute
  '/services/injectables': typeof ServicesInjectablesRoute
  '/services/laser': typeof ServicesLaserRoute
  '/services/lifting': typeof ServicesLiftingRoute
  '/services/skin': typeof ServicesSkinRoute
  '/services/surgery': typeof ServicesSurgeryRoute
  '/services/wellness': typeof ServicesWellnessRoute
  '/services/': typeof ServicesIndexRoute
  '/services/dental/cosmetic-dentistry': typeof ServicesDentalCosmeticDentistryRoute
  '/services/dental/general': typeof ServicesDentalGeneralRoute
  '/services/dental/implants': typeof ServicesDentalImplantsRoute
  '/services/dental/orthodontics': typeof ServicesDentalOrthodonticsRoute
  '/services/dental/whitening': typeof ServicesDentalWhiteningRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/services'
    | '/services/aesthetic'
    | '/services/injectables'
    | '/services/laser'
    | '/services/lifting'
    | '/services/skin'
    | '/services/surgery'
    | '/services/wellness'
    | '/services/'
    | '/services/dental/cosmetic-dentistry'
    | '/services/dental/general'
    | '/services/dental/implants'
    | '/services/dental/orthodontics'
    | '/services/dental/whitening'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/services/aesthetic'
    | '/services/injectables'
    | '/services/laser'
    | '/services/lifting'
    | '/services/skin'
    | '/services/surgery'
    | '/services/wellness'
    | '/services'
    | '/services/dental/cosmetic-dentistry'
    | '/services/dental/general'
    | '/services/dental/implants'
    | '/services/dental/orthodontics'
    | '/services/dental/whitening'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/services'
    | '/services/aesthetic'
    | '/services/injectables'
    | '/services/laser'
    | '/services/lifting'
    | '/services/skin'
    | '/services/surgery'
    | '/services/wellness'
    | '/services/'
    | '/services/dental/cosmetic-dentistry'
    | '/services/dental/general'
    | '/services/dental/implants'
    | '/services/dental/orthodontics'
    | '/services/dental/whitening'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  ServicesRoute: typeof ServicesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/wellness': {
      id: '/services/wellness'
      path: '/wellness'
      fullPath: '/services/wellness'
      preLoaderRoute: typeof ServicesWellnessRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/surgery': {
      id: '/services/surgery'
      path: '/surgery'
      fullPath: '/services/surgery'
      preLoaderRoute: typeof ServicesSurgeryRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/skin': {
      id: '/services/skin'
      path: '/skin'
      fullPath: '/services/skin'
      preLoaderRoute: typeof ServicesSkinRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/lifting': {
      id: '/services/lifting'
      path: '/lifting'
      fullPath: '/services/lifting'
      preLoaderRoute: typeof ServicesLiftingRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/laser': {
      id: '/services/laser'
      path: '/laser'
      fullPath: '/services/laser'
      preLoaderRoute: typeof ServicesLaserRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/injectables': {
      id: '/services/injectables'
      path: '/injectables'
      fullPath: '/services/injectables'
      preLoaderRoute: typeof ServicesInjectablesRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/aesthetic': {
      id: '/services/aesthetic'
      path: '/aesthetic'
      fullPath: '/services/aesthetic'
      preLoaderRoute: typeof ServicesAestheticRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/dental/whitening': {
      id: '/services/dental/whitening'
      path: '/dental/whitening'
      fullPath: '/services/dental/whitening'
      preLoaderRoute: typeof ServicesDentalWhiteningRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/dental/orthodontics': {
      id: '/services/dental/orthodontics'
      path: '/dental/orthodontics'
      fullPath: '/services/dental/orthodontics'
      preLoaderRoute: typeof ServicesDentalOrthodonticsRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/dental/implants': {
      id: '/services/dental/implants'
      path: '/dental/implants'
      fullPath: '/services/dental/implants'
      preLoaderRoute: typeof ServicesDentalImplantsRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/dental/general': {
      id: '/services/dental/general'
      path: '/dental/general'
      fullPath: '/services/dental/general'
      preLoaderRoute: typeof ServicesDentalGeneralRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/dental/cosmetic-dentistry': {
      id: '/services/dental/cosmetic-dentistry'
      path: '/dental/cosmetic-dentistry'
      fullPath: '/services/dental/cosmetic-dentistry'
      preLoaderRoute: typeof ServicesDentalCosmeticDentistryRouteImport
      parentRoute: typeof ServicesRoute
    }
  }
}

interface ServicesRouteChildren {
  ServicesAestheticRoute: typeof ServicesAestheticRoute
  ServicesInjectablesRoute: typeof ServicesInjectablesRoute
  ServicesLaserRoute: typeof ServicesLaserRoute
  ServicesLiftingRoute: typeof ServicesLiftingRoute
  ServicesSkinRoute: typeof ServicesSkinRoute
  ServicesSurgeryRoute: typeof ServicesSurgeryRoute
  ServicesWellnessRoute: typeof ServicesWellnessRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
  ServicesDentalCosmeticDentistryRoute: typeof ServicesDentalCosmeticDentistryRoute
  ServicesDentalGeneralRoute: typeof ServicesDentalGeneralRoute
  ServicesDentalImplantsRoute: typeof ServicesDentalImplantsRoute
  ServicesDentalOrthodonticsRoute: typeof ServicesDentalOrthodonticsRoute
  ServicesDentalWhiteningRoute: typeof ServicesDentalWhiteningRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesAestheticRoute: ServicesAestheticRoute,
  ServicesInjectablesRoute: ServicesInjectablesRoute,
  ServicesLaserRoute: ServicesLaserRoute,
  ServicesLiftingRoute: ServicesLiftingRoute,
  ServicesSkinRoute: ServicesSkinRoute,
  ServicesSurgeryRoute: ServicesSurgeryRoute,
  ServicesWellnessRoute: ServicesWellnessRoute,
  ServicesIndexRoute: ServicesIndexRoute,
  ServicesDentalCosmeticDentistryRoute: ServicesDentalCosmeticDentistryRoute,
  ServicesDentalGeneralRoute: ServicesDentalGeneralRoute,
  ServicesDentalImplantsRoute: ServicesDentalImplantsRoute,
  ServicesDentalOrthodonticsRoute: ServicesDentalOrthodonticsRoute,
  ServicesDentalWhiteningRoute: ServicesDentalWhiteningRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  ServicesRoute: ServicesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
